Models/Account.cs
namespace clubrainbow.Models
{
    public class Account
    {
        public int Id { get; set; } 
        public string? Username { get; set; } 
        public string? Email { get; set; }
        public DateTime CreatedDate { get; set; } 

    }
}

Models/ErrorViewModel.cs
namespace clubrainbow.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/AccountController.cs
using clubrainbow.Data;
using clubrainbow.Models;
using Microsoft.AspNetCore.Mvc;

namespace clubrainbow.Controllers
{
    public class AccountController : Controller
    {
        private readonly ApplicationDbContext _context;
        [HttpGet]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Login(string email, string password)
        {
            
            if (email == "clubrainbow@gmail.com" && password == "password")
            {
                
                return RedirectToAction("Msg", "VerifyMsg");
            }

            ViewBag.Message = "Invalid email or password.";
            return View();
        }

        public AccountController(ApplicationDbContext context)
        {
            _context = context;
        }

      
        public async Task<IActionResult> AddAccount()
        {
            Console.WriteLine("AddAccount method is being called");


            var account = new Account
            {
                Username = "johnDoe",
                Email = "johndoe@example.com", 
                CreatedDate = DateTime.Now 
            };

            _context.Account.Add(account);

           
            await _context.SaveChangesAsync();

            return Ok("Account added successfully");
        }
    }
}

Controllers/HomeController.cs
using clubrainbow.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace clubrainbow.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PasswordController.cs
using Microsoft.AspNetCore.Mvc;

namespace clubrainbow.Controllers
{
	public class PasswordController : Controller
	{
		public IActionResult ResetPassword()
		{
			return View();
		}
        public IActionResult checkyouremail()
        {
            return View();
        }

        public IActionResult newpassword()
        {
            return View();
        }

        public IActionResult passwordchanged()
        {
            return View();
        }
    }
}

Controllers/VerifyMsgController.cs
using Microsoft.AspNetCore.Mvc;

namespace clubrainbow.Controllers
{
    public class VerifyMsgController : Controller
    {
        public IActionResult Msg()
        {
            return View();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Home/test.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Views/Password/ResetPassword.cshtml
@{
    ViewData["Title"] = "ResetPassword";
}
<h3>ResetPassword</h3>

<a href="@Url.Action("checkyouremail", "Password")">send</a>

Views/Password/checkyouremail.cshtml
@page
<h3>checkyouremail</h3>

Views/Password/newpassword.cshtml
<h3>Newpassword</h3>
<h2>create your new password , so you can login to your account </h2>


<div>
	<a href="@Url.Action("passwordchanged", "Password")">Submit</a>

</div>

Views/Password/passwordchanged.cshtml
<h3>password changed</h3>

<h2>password changed successfully,you can loging again with a new password</h2>

<div>
	<a href="@Url.Action("login", "Account")">login page</a>

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - clubrainbow</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/clubrainbow.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">clubrainbow</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Password" asp-action="newpassword">newpassword</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - clubrainbow - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/VerifyMsg/msg.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@{
    ViewData["Title"] = "check your email";
}
<h3>check you email</h3>